Redesign/components button
Peersyst/ckbull-mobile pull request #411
Opened 2023-01-30 11:43 UTC by silvap-javier

# Redesign: Components - Button

## Issues

closes #400 

## Changes

- Change styles of variants buttons

## Dependencies
#409

2023-01-31 07:52 UTC, AgustinMJ requested changes

2023-01-31 07:52 UTC, AgustinMJ commented on src/module/common/component/input/Button/Button.styles.ts
> +                color: theme.palette.white,
La variant de text sí que tiene que ser `theme.palette.text`

2023-01-31 07:52 UTC, AgustinMJ commented on src/module/common/component/input/Button/Button.styles.ts
> +            backgroundColor: theme.palette.overlay[100]["12%"],
Esto no afecta a la variant text disabled? No sé si es del todo correcto definir este backgroundColor aquí i no por variants

2023-01-31 07:52 UTC, AgustinMJ commented on src/module/common/component/input/Button/Button.styles.ts
> +export const ButtonGradient = styled(Animated.createAnimatedComponent(classify(LinearGradient)))(() => ({
Por qué es animated?

2023-01-31 07:52 UTC, AgustinMJ commented on src/module/common/component/input/Button/Button.tsx
> +    const { variant, disabled } = rest;
Por qué este variant y disabled no se saca con el style? Creo que esta línea es redundante

2023-01-31 07:52 UTC, AgustinMJ commented on src/module/common/component/input/Button/Button.styles.ts
>                      backgroundColor: emphasize(theme.palette.primary, 0.15),
No se ve bien este pressed, yo le pondría el overlay 100 con menos opacidad a ver cómo queda

2023-01-31 07:52 UTC, AgustinMJ commented on src/module/common/component/input/Button/Button.styles.ts
> +                    backgroundColor: emphasize(theme.palette.black, 0.02),
Habría que hacer el emphasize con `theme.palette.gray[900]` que es el color que tiene la variant secondary

2023-01-31 07:52 UTC, AgustinMJ commented on src/module/common/component/input/Button/Button.styles.ts
>                  color: theme.palette.text,
El outlined no tiene este color de borderColor

2023-01-31 07:52 UTC, AgustinMJ commented on src/module/common/component/input/Button/Button.types.ts
> +    style?: Omit<ViewStyle, "backgroundColor"> & { backgroundColor?: string; secondaryBackgroundColor?: string };
Le podemos quitar el backgroundColor del style y ya está, no debería hacer falta modificarlo, si hiciera falta es que hay una variant nueva, así evitamos poner `{ backgroundColor?: string; secondaryBackgroundColor?: string }`

2023-01-31 07:52 UTC, AgustinMJ commented on src/module/common/component/layout/ImageBackgroundPage/ImageBackgroundPage.styles.ts
> +    height: "100%",
dimensions.height ya estaba bien creo

2023-01-31 12:28 UTC, silvap-javier commented on src/module/common/component/input/Button/Button.styles.ts
>                  color: theme.palette.text,
Done

2023-01-31 12:28 UTC, silvap-javier commented on src/module/common/component/input/Button/Button.styles.ts
> +                    backgroundColor: emphasize(theme.palette.black, 0.02),
Done

2023-01-31 12:28 UTC, silvap-javier commented on src/module/common/component/input/Button/Button.styles.ts
> +            backgroundColor: theme.palette.overlay[100]["12%"],
Done, lo he sacado y lo dejamos por cada variants

2023-01-31 12:28 UTC, silvap-javier commented on src/module/common/component/input/Button/Button.types.ts
> +    style?: Omit<ViewStyle, "backgroundColor"> & { backgroundColor?: string; secondaryBackgroundColor?: string };
Done

2023-01-31 12:28 UTC, silvap-javier commented on src/module/common/component/layout/ImageBackgroundPage/ImageBackgroundPage.styles.ts
> +    height: "100%",
Resuelto en la PR de Logo Page :)

2023-02-01 09:48 UTC, AgustinMJ approved these changes

2023-02-01 10:19 UTC, merged