Redesign: Components - Modal
Peersyst/ckbull-mobile pull request #413
Opened 2023-01-31 07:31 UTC by GuillemGarciaDev

## Redesign: Components - Modal

## Issue

closes #376 

## Changes

- CardNavigatorModal (added logic and structure from `near-wallet`)
- CardModal 
- CardSelectModal (for actions "close" and "hide")
- tests

2023-02-01 07:23 UTC, JordiParraCrespo requested changes

2023-02-01 07:23 UTC, JordiParraCrespo commented on src/module/common/component/feedback/CardSelectModal/CardSelectModal.tsx
> +    const actionIcons = {
Està super igual faria una mini millora
```
export type CardSelectModalAction = "hide" | "close";
...
const ACTION_ICONS: Record<CardSelectModalAction, typeof ChevronDownIcon> = { ... } 
```
I els ACTION_ICONS si els fiques fora del component no es crean a cada render com a mini millora

2023-02-01 07:23 UTC, JordiParraCrespo commented on src/module/common/component/display/Steps/Steps.tsx
> +        <Typography variant="body3Light" light>
La variant light crec q no s'està aplicant correctament

2023-02-01 07:24 UTC, JordiParraCrespo requested changes

2023-02-01 07:24 UTC, JordiParraCrespo commented on src/module/common/component/navigation/Navbar/Navbar.tsx
> +                    <Typography style={{ lineHeight: 30 }} variant="body1Light" textTransform="uppercase">
la `lineHeight` si falla s'hauria de posar al `typography.ts`

2023-02-01 07:41 UTC, JordiParraCrespo requested changes

2023-02-01 07:41 UTC, JordiParraCrespo commented on src/config/theme/lightTheme.ts
> +        background: gray[100],
Aquí hi ha discrepancias amb la pr del pablo igual la card. S'hauria d'unificar si no tmb es pot afegir una variable al theme pero no hauria de fer falta.

2023-02-02 16:46 UTC, GuillemGarciaDev commented on src/module/common/component/feedback/CardSelectModal/CardSelectModal.tsx
> +    const actionIcons = {
Donete

2023-02-02 16:58 UTC, GuillemGarciaDev commented on src/module/common/component/navigation/Navbar/Navbar.tsx
> +                    <Typography style={{ lineHeight: 30 }} variant="body1Light" textTransform="uppercase">
L'he suplit amb un gap per ara

2023-02-02 16:59 UTC, GuillemGarciaDev commented on src/module/common/component/display/Steps/Steps.tsx
> +        <Typography variant="body3Light" light>
He comprovat el color al figma i he acabat fent `theme.palette.gray[light ? 200 : 700]`

2023-02-03 07:05 UTC, JordiParraCrespo commented on src/module/common/component/navigation/Navbar/Navbar.tsx
> +                    <Typography style={{ lineHeight: 30 }} variant="body1Light" textTransform="uppercase">
Millor canviarho al theme no? Xq si no amb la mateixa variant no es veurà bé a altres llocs de la app no?

2023-02-03 08:48 UTC, GuillemGarciaDev commented on src/module/common/component/navigation/Navbar/Navbar.tsx
> +                    <Typography style={{ lineHeight: 30 }} variant="body1Light" textTransform="uppercase">
Però no a tots els llocs el lineHeight es de 30 🤔

2023-02-03 08:52 UTC, GuillemGarciaDev commented on src/config/theme/lightTheme.ts
> +        background: gray[100],
Casi que utilitzaré un altre variable així ja queda definida també

2023-02-03 12:09 UTC, JordiParraCrespo approved these changes

2023-02-03 12:15 UTC, merged