Redesign/auth setmame screen
Peersyst/ckbull-mobile pull request #414
Opened 2023-01-31 08:07 UTC by silvap-javier

# Redesign/auth setmame screen

## Issues

closes #402  

## Changes

- Add set name step in create and importante wallet

## Dependencies

#400

2023-02-01 07:43 UTC, JordiParraCrespo requested changes
Esta pr debería tirar de la de guillem ya que los cambios en el modal mejor unificarlos en una misma pr.

2023-02-01 07:43 UTC, JordiParraCrespo commented on src/module/common/component/input/PadItem/PadItem.styles.ts
> +        marginBottom: -3,
Esto creo q se debe al lineHeight de la typo

2023-02-01 07:43 UTC, JordiParraCrespo commented on src/module/wallet/navigator/ImportWalletNavigatorGroup.tsx
>                  >
Lo mismo aquí con le orden

2023-02-01 07:43 UTC, JordiParraCrespo commented on src/module/common/component/display/Steps/Steps.tsx
> +        <Typography variant="body3Regular" color={(palette) => palette.gray[700]}>{` ${length}`}</Typography>
Tmb los dos números han de ser del mismo tamaño

2023-02-01 07:43 UTC, JordiParraCrespo commented on src/config/theme/lightTheme.ts
> +        background: gray[0],
Aquí hay discrepancias con la pr de Guillem.

2023-02-02 16:52 UTC, silvap-javier commented on src/config/theme/lightTheme.ts
> +        background: gray[0],
no se cual Pr dices, actualmente esta todo actualizado con dev y no tiene problemas

2023-02-02 16:52 UTC, silvap-javier commented on src/module/common/component/display/Steps/Steps.tsx
> +        <Typography variant="body3Regular" color={(palette) => palette.gray[700]}>{` ${length}`}</Typography>
Done

2023-02-02 16:52 UTC, silvap-javier commented on src/module/wallet/navigator/CreateWalletNavigatorGroup.tsx
> +        if (activeTab === CreateWalletScreens.SET_WALLET_NAME) {
Esto ya te lo comente, que asi estaban en los diseños

2023-02-02 16:52 UTC, silvap-javier commented on src/module/wallet/navigator/ImportWalletNavigatorGroup.tsx
>                  >
Done

2023-02-03 14:23 UTC, JordiParraCrespo approved these changes

2023-02-03 14:23 UTC, merged