Redisign/create and import wallet
Peersyst/ckbull-mobile pull request #424
Opened 2023-02-01 17:11 UTC by silvap-javier

# Redesign: Create and import wallet steps

## Issues

closes #380 

## Dependencies

#402

## Changes

- Check and complete flow create wallet and import
- Redesign component chip

2023-02-03 14:33 UTC, JordiParraCrespo requested changes

2023-02-03 14:33 UTC, JordiParraCrespo commented on src/locale/locales/es/common.json
> +    "set_pin": "Introduce un PIN",
bien =)

2023-02-03 14:33 UTC, JordiParraCrespo commented on src/module/common/component/display/AdviseGroup/AdviseGroup.tsx
> +        <PagerView page={index} onPageSelected={setIndex} showPageIndicator height={200} gap={24} onStartShouldSetResponder={() => true}>
Como antes q si no se corta el texto

2023-02-03 14:33 UTC, JordiParraCrespo commented on src/module/common/component/display/Chip/Chip.styles.ts
> +        borderColor: theme.palette.mode === "dark" ? "transparent" : theme.palette.overlay[700]["8%"],
Revisalo de nuevo con los cambios del theme

2023-02-06 08:24 UTC, silvap-javier commented on src/module/common/component/display/AdviseGroup/AdviseGroup.tsx
> +        <PagerView page={index} onPageSelected={setIndex} showPageIndicator height={200} gap={24} onStartShouldSetResponder={() => true}>
Done

2023-02-13 06:54 UTC, JordiParraCrespo approved these changes

2023-02-13 07:07 UTC, merged