Signer feature: Transaction Request component
Peersyst/ckbull-mobile pull request #438
Opened 2023-02-06 09:33 UTC by GuillemGarciaDev

# Signer feature: Transaction Request component

## Issues

closes #394 

## Changes

- TransactionRequest (component that uses ActivityCard)
- ActivityCard (changes to adapt amount of TransactionRequest)
- DAOTabs (just to show the component)
- testing + commons
- time.ts (contains function to show expirationTime of the TransactionRequest)

2023-02-06 10:04 UTC, AgustinMJ commented on src/module/activity/component/display/ConnectedSite/ConnectedSite.tsx
> +            display={<ActivityDisplay source={source ? { uri: source } : placeholder_image} />}
Més que rebre el ActivityDisplay de ActivityCard, la prop de display hauria d'acceptar la uri com vam dir, així és ActivityCard qui s'ocupa de la size i l'estil de l'ActivityDisplay

2023-02-06 10:08 UTC, AgustinMJ commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.types.ts
> +    transaction: Pick<Transaction, "type" | "amount">; //Add inputs & outputs
El comment és perquè encara no està clar com anirà això dels inputs i outputs, no?

2023-02-06 10:11 UTC, AgustinMJ commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.types.ts
> +    app?: App;
Tots aquests types que seran DTOs és millor ficar-los tots junts en un arxiu temporal a la carpeta activity. Per exemple, dtos.ts o algo així, ja que després es canviaran pels auto generats del backend i serà més senzill. També pots posar-li el nom que tindran aquests DTOs auto generats perquè sigui encara més fàcil, per exemple: AppDto i TransactionDto (el type de la transaction no serà el mateix que una transacció del sdk)

2023-02-06 10:12 UTC, AgustinMJ commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.tsx
> +        app: { title, source = "" } = { title: "" },
Crec que això ho hauria d'haver dit en una altra pr però potser millor que source, image o imageUrl o algo així pot ser més descriptiu

2023-02-06 10:15 UTC, AgustinMJ commented on src/module/activity/core/ActivityCard/ActivityCard.tsx
> +            {amount}
Per què l'ammount pot ser un ReactElement? L'amount s'hauria de rebre sempre en string i renderitzar un component de Balance sempre igual, no?
També si es fa això de string | number | ReactElement, pensa que a React Native si renderitzes un string sense un Text peta, així que en aquests casos s'hauria de handlejar això

2023-02-06 10:27 UTC, AgustinMJ commented on src/module/activity/utils/time.ts
> +export const getTimeFromSeconds = (seconds: number): GetTimeReturn => {
El nom de les variables potser estaria millor d'una altra manera, ja que no estem fent cap formatting. Podem fer aquests canvis en les variables:
- seconds -> totalSeconds
- formatedSeconds -> seconds
- formattedHours -> hours
- formattedMinutes -> minutes
- return { hours, minutes, seconds }

2023-02-06 10:31 UTC, AgustinMJ requested changes
Dummy comment to request changes (He ficat els comments malament sense volguer i no em deixa fer request changes si no fico aquest comment jajja)

2023-02-06 11:05 UTC, GuillemGarciaDev commented on src/module/activity/component/display/ConnectedSite/ConnectedSite.tsx
> +            display={<ActivityDisplay source={source ? { uri: source } : placeholder_image} />}
True, done

2023-02-06 11:06 UTC, GuillemGarciaDev commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.types.ts
> +    transaction: Pick<Transaction, "type" | "amount">; //Add inputs & outputs
Si correcte, encara està subjecte a canvis

2023-02-06 11:22 UTC, GuillemGarciaDev commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.tsx
> +        app: { title, source = "" } = { title: "" },
Done

2023-02-06 11:25 UTC, GuillemGarciaDev commented on src/module/activity/utils/time.ts
> +export const getTimeFromSeconds = (seconds: number): GetTimeReturn => {
done

2023-02-06 11:31 UTC, GuillemGarciaDev commented on src/module/activity/core/ActivityCard/ActivityCard.tsx
> +            {amount}
Tens raó amb el `string`. He posat ReactElement per a no haver de gestionar lògica del balance dins del ActivityCard, com per exemple, el TransactionAmount gestiona dins el color del balance segons la transaction en comptes de passar-ho com a prop com "amountType" o així

Això sí, si es deixa el ReactElement es treuríen el number i el string com a types del amount

2023-02-06 11:42 UTC, GuillemGarciaDev commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.types.ts
> +    app?: App;
Nice, no els puc definir tots encara però els que relacionen amb TransactionRequest llestos

2023-02-06 13:45 UTC, AgustinMJ commented on src/module/activity/core/ActivityCard/ActivityCard.tsx
> +            {amount}
Crec que és millor que la ActivityCard renderitzi el balance i si es vol canviar el color que es faci amb el style com els altres slots, podem posar un camp d'amount al style

2023-02-06 15:51 UTC, GuillemGarciaDev commented on src/module/activity/core/ActivityCard/ActivityCard.tsx
> +            {amount}
Done

2023-02-07 07:16 UTC, AgustinMJ approved these changes

2023-02-07 07:16 UTC, merged