ActivityScreen with tabs
Peersyst/ckbull-mobile pull request #440
Opened 2023-02-06 16:40 UTC by GuillemGarciaDev

# ActivityScreen with tabs

## Issues

closes #398 
closes #391
closes #390 
closes #396

## Dependencies

#438 

## Changes

- ActivityScreen (using BaseMainScreen)(dummy view to represent search bar)
- ActivityTabs
- PendingTransactionsList (shows every TransactionRequest with status "pending")
- SignedTransactionsList (shows every signed Transaction)
- useGetPendingTransactionsRequest (mocked call that returns every TransactionRequest in "pending" status)
- useGetSignedTransactionRequest (mocked call that returns every Transaction that has been signed)
- useGetDateFromTimestamp (hook to format timestamp to dates)
- MainSectionList (main component used in PendingTransactionsList)
- commons + tests

2023-02-07 08:08 UTC, AgustinMJ requested changes

2023-02-07 08:08 UTC, AgustinMJ commented on src/module/activity/screen/ActivityScreen.tsx
> +            <View style={{ backgroundColor: "gray", height: 60, marginTop: 20, marginBottom: 40 }}></View>
Aquest espai serà pel cercador, oi?

2023-02-07 08:08 UTC, AgustinMJ commented on test/unit/src/module/activity/component/display/ConnectedSiteList/ConnectedSiteList.spec.tsx
> +        render(<ConnectedSiteList />);
A ckbull/near no és tan important perquè tots els components estan fets així. Però potser estaria bé començar a pensar en components i containers. En aquest cas, el component seria la ConnectedSiteList que acceptaria un array de ConnectedSite, un loading, etc i el container seria un component que fes la crida i li passes aquesta llista al component. No ho dic per ara, ja que és feina i no cal en aquest projecte, però per començar a provar aquest patró per veure com ens funciona en els proper components jeje

2023-02-07 08:59 UTC, GuillemGarciaDev commented on test/unit/src/module/activity/component/display/ConnectedSiteList/ConnectedSiteList.spec.tsx
> +        render(<ConnectedSiteList />);
Doncs si estaría bé 👍🏻

2023-02-07 09:04 UTC, GuillemGarciaDev commented on src/module/activity/hook/useGetDateFromTimestamp.ts
> +export default function (): UseGetDateFromTimestamp {
done

2023-02-07 09:10 UTC, GuillemGarciaDev commented on src/module/activity/component/display/PendingTransactionsList/PendingTransactionsList.tsx
> +    const renderSectionHeader = ({ section: { title } }: any): JSX.Element => {
done

2023-02-07 09:13 UTC, GuillemGarciaDev commented on src/module/activity/component/display/PendingTransactionsList/PendingTransactionsList.styles.ts
> +    justifyContent: "flex-start",
Done

2023-02-07 09:16 UTC, GuillemGarciaDev commented on src/module/activity/queries/useGetPendingTransactionRequest.ts
> +export default function (): QueryResult<readonly SectionListData<TransactionRequestDto, PendingTransactionRequests>[]> {
Li vaig posar aquest nom per a que no hi hagués confusió amb les Transactions normals que poden tindre també status `pending`, però com no hi ha cap hook igual es pot posar com dius 👍🏻

2023-02-07 09:16 UTC, GuillemGarciaDev commented on src/module/activity/queries/useGetSignedTransactionRequest.ts
> +export default function (): QueryResult<FullTransaction[]> {
done

2023-02-07 09:17 UTC, GuillemGarciaDev commented on src/module/activity/screen/ActivityScreen.tsx
> +            <View style={{ backgroundColor: "gray", height: 60, marginTop: 20, marginBottom: 40 }}></View>
Sii

2023-02-07 09:17 UTC, GuillemGarciaDev commented on src/query/queries.ts
> +    GET_PENDING_TRANSACTION_REQUEST,
Bona idea

2023-02-07 09:19 UTC, GuillemGarciaDev commented on src/query/queries.ts
> +    GET_PENDING_TRANSACTION_REQUEST,
done

2023-02-07 09:19 UTC, GuillemGarciaDev commented on src/query/queries.ts
> +    GET_PENDING_TRANSACTION_REQUEST,
Done

2023-02-07 09:56 UTC, GuillemGarciaDev commented on src/module/activity/component/display/PendingTransactionsList/PendingTransactionsList.tsx
> +                <Typography variant="body3Strong">{formatDate(title)}</Typography>
Done

2023-02-07 09:56 UTC, GuillemGarciaDev commented on src/module/activity/queries/useGetPendingTransactionRequest.ts
> +    return useQuery([Queries.GET_PENDING_TRANSACTION_REQUEST, usedIndex, network], getMockTransactionRequest, {
Done

2023-02-09 08:51 UTC, AgustinMJ requested changes

2023-02-09 08:51 UTC, AgustinMJ commented on src/module/main/component/display/MainSectionList/MainSectionList.tsx
> +    const renderSectionHeader = ({ section: { title } }: any): JSX.Element => {
Això no hauria de ser any🤔

2023-02-09 08:51 UTC, AgustinMJ commented on src/module/activity/hook/useGetParsedPendingTransactions.ts
> +    return useMemo(() => {
En comptes d'un useMemo pots retornar la mateixa `useGetPendingTransactions` amb la opció `select` que accepta el `useQuery`. Per fer-ho hauràs de fer que `useGetPendingTransactions` accepti les opcions del `useQuery`, em sembla que hi ha un type fet a `react-query-overrides.ts` i exemples a altres queries

```ts
return useGetPendingTransactions({ select: (data) => /* Codi que transforma les dades */});
```

2023-02-09 10:23 UTC, AgustinMJ approved these changes

2023-02-09 10:28 UTC, merged