Add wallet
Peersyst/ckbull-mobile pull request #473
Opened 2023-02-21 08:55 UTC by silvap-javier

# Redesign: Home - Add wallet

## Issues

closes #401 

## Dependencies

#

## Changes

- Add new view for add Wallet step

2023-02-21 14:49 UTC, JordiParraCrespo requested changes

2023-02-21 22:51 UTC, silvap-javier commented on src/module/wallet/component/core/AddWallet/AddWallet.styles.ts
> +    backgroundColor: theme.palette.mode === "light" ? theme.palette.gray[0] : theme.palette.gray[50],
Done

2023-02-21 22:51 UTC, silvap-javier commented on src/config/theme/lightTheme.ts
> +    50: "#191919",
Done

2023-02-22 07:46 UTC, JordiParraCrespo approved these changes

2023-02-22 07:46 UTC, merged