Signer Feature: Fetch Connected Sites list
Peersyst/ckbull-mobile pull request #515
Opened 2023-03-23 08:56 UTC by GuillemGarciaDev

# Signer Feature: Fetch Connected Sites list

## Issues

#close 57

## Changes

- Configured OpenApiConfig + base config
- useGetConnectedSites
- ConnectedSite component
- ConnectedSiteList
- testing update + translate

2023-03-28 14:23 UTC, GuillemGarciaDev commented on src/config/config.dev.json
> +    "signerUrl": "http://192.168.1.55:3001"
Expo Go private IP for simulator localhost (add comment)

2023-03-31 07:07 UTC, JordiParraCrespo requested changes

2023-03-31 07:07 UTC, JordiParraCrespo commented on src/module/api/service/models/CompleteDAppDto.ts
> +    apiSecret: string;
Crec la diferencia entre el `Partial` i el `Complete` es només el `apiSecret` que crec q al frontend no s'ha de canviar. X tant igual faria. `DappDto` i `DappWithApiSecretDto` o algo així.

2023-03-31 07:07 UTC, JordiParraCrespo commented on src/module/api/service/models/PartialDappDto.ts
> +export type PartialDappDto = {
Crec q això està dos cops el mateix no?

2023-03-31 07:07 UTC, JordiParraCrespo commented on src/module/api/service/models/SecretDto.ts
> +export type SecretDto = {
S'han duplicat els Dtos no?

2023-03-31 08:13 UTC, GuillemGarciaDev commented on src/module/api/service/models/CompleteDAppDto.ts
> +    apiSecret: string;
No s'utilitza a mobile

2023-03-31 08:25 UTC, GuillemGarciaDev commented on src/module/api/common/models/PartialDappDto.ts
> +export type PartialDappDto = {
No s'utilitza tampoc

2023-04-06 09:24 UTC, JordiParraCrespo approved these changes

2023-04-06 09:25 UTC, merged