Signer Feature: Complete Sign In Request Modal
Peersyst/ckbull-mobile pull request #516
Opened 2023-03-26 18:13 UTC by GuillemGarciaDev

# Signer Feature: Complete Sign In Request Modal

## Issues

closes #504 #509 #510 

## Changes

- SignInRequestDetails
- SignInRequestModal
- SignRequestModal
- useSignSignInRequest
- useRejectSignInRequest
- SignRequestModalLayout
- testing + locale

2023-03-31 08:07 UTC, JordiParraCrespo requested changes

2023-03-31 08:07 UTC, JordiParraCrespo commented on src/module/activity/screen/SignInRequestScreen/SignInRequestScreen.tsx
> +
```
const SignInRequestScreen = ({ signInRequest }: SignInRequestScreenProps): JSX.Element => {
    const { name, description, image } = signInRequest.app;
    const { signInToken } = signInRequest;

    const { hideModal } = useModal();
    const translate = useTranslate();
    const [formWallet, setFormWallet] = useState<number | undefined>(undefined);

    const { serviceInstance, network } = useServiceInstance(formWallet);
    const { mutate: sign, isLoading: isSigning, isError: isSignError, isSuccess: isSignSuccess } = useSignSignInRequest(signInToken);
    const { mutate: decline, isLoading: isDeclining } = useRejectSignInRequest(signInToken);
    const isModalLoading = isSigning || isDeclining;

    const closeSignInRequestModal = () => {
        hideModal(SignInRequestModal.id);
    };

    const handleReject = () => {
        decline();
        closeSignInRequestModal();
    };

    const handleOnPinConfirmed = () => {
        const address = serviceInstance?.getAddress();
        const metadata = { address: address!, network };
        sign({ metadata });
    };

    return (
        <SignRequestModal
            signRequest={handleOnPinConfirmed}
            isLoading={isSigning}
            isError={isSignError}
            isSuccess={isSignSuccess}
            onExited={isSignSuccess || isSignError ? closeSignInRequestModal : undefined}
            successMessage={translate("signInRequestSuccess")}
        >
            {({ showModal, isSuccess }) => (
                <SignRequestModalLayout onReject={handleReject} onSign={showModal} loading={isModalLoading} disabled={isSuccess}>
                    <SignInRequestDetails
                        name={name}
                        image={image}
                        description={description}
                        loading={isModalLoading}
                        selectedWallet={formWallet}
                        onWalletChange={setFormWallet}
                    />
                </SignRequestModalLayout>
            )}
        </SignRequestModal>
    );
};

export default SignInRequestScreen;
```

2023-03-31 08:07 UTC, JordiParraCrespo commented on src/module/activity/screen/SignInRequestScreen/SignInRequestScreen.tsx
> +
Jo ho ordeinaria així que crec q es llegeix una mica millor el codi.

2023-04-05 07:12 UTC, GuillemGarciaDev commented on src/module/activity/component/display/SignInRequestDetails/SignInRequestDetails.tsx
> +                name="signer"
Potser no cal no? Pensa que aquest component únicament es per al signInRequest

2023-04-05 13:47 UTC, GuillemGarciaDev commented on src/module/common/component/input/MainButton/MainButton.tsx
> +    const handleSuccess = (request: SignInRequestDto) => showModal(SignInRequestModal, { signInRequest: request });
Done

2023-04-05 13:51 UTC, GuillemGarciaDev commented on src/module/common/component/input/MainButton/MainButton.tsx
> +    const handleSuccess = (request: SignInRequestDto) => showModal(SignInRequestModal, { signInRequest: request });
Done

2023-04-06 09:20 UTC, JordiParraCrespo requested changes

2023-04-06 09:20 UTC, JordiParraCrespo commented on src/module/common/component/input/MainButton/MainButton.tsx
> +    const [, setSendState] = useRecoilState(sendState);
`useSetRecoilState`

2023-04-06 09:20 UTC, JordiParraCrespo commented on src/module/common/hook/useAddressValidator.ts
> +    return network === "mainnet" ? mainnetAddressValidator.validate : testnetAddressValidator.validate;
Retornar només un validator

2023-04-06 09:20 UTC, JordiParraCrespo commented on src/module/dao/screen/WithdrawConfirmationScreen/WithdrawConfirmationScreen.tsx
> +        <CallbackModal
SignModal

2023-04-06 09:20 UTC, JordiParraCrespo commented on src/module/activity/screen/SignInRequestScreen/SignInRequestScreen.tsx
> +                    signingDisabled={isSuccess || isSignSuccess}
`isSignIng` o `isRejecting` i ficaria `isSuccess`

2023-04-06 09:20 UTC, JordiParraCrespo commented on src/module/activity/screen/SignInRequestScreen/SignInRequestScreen.tsx
> +            onExited={isSignSuccess || isSignError ? closeSignInRequestModal : undefined}
Revisar o sino ficar un comment

2023-04-11 07:34 UTC, JordiParraCrespo approved these changes

2023-04-11 07:35 UTC, merged