Signer Feature: Fetch pending Transaction Requests
Peersyst/ckbull-mobile pull request #517
Opened 2023-03-28 08:46 UTC by GuillemGarciaDev

# Signer Feature: Fetch pending Transaction Requests

## Issues

closes #502 

## Dependencies

#516 

## Changes

- PendingTransactionRequestsList (updated with new dtos) + test update
- activity/types.ts
- TransactionRequest (updated with new dtos) + test update
- useGetPendingTransactions (query update)
- utils/time.ts
- complete-transaction-request-dto.mock
- account-metadata-dto.mock
- sign-in-request-dto.mock

2023-03-31 08:27 UTC, JordiParraCrespo requested changes

2023-03-31 08:27 UTC, JordiParraCrespo commented on src/locale/locales/el/common.json
> +    "signInRequestSuccess": "Sign in request signed successfully!",
Aquí ficaria algo més user friendly com `Logged in successfully` o així no?

2023-03-31 08:27 UTC, JordiParraCrespo commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.styles.ts
> +    const action = "add";
Aquí si ara sempre es add ficaria que directament et surti el color. A part el color hauria de ser el `primary` no el green. Si pots revisa si algún altre lloc hi ha lo del `green[200]`

2023-03-31 08:27 UTC, JordiParraCrespo commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.tsx
> +            details={expiresAt ? translate("expireDate", getTimeFromSeconds(expirationTimestamp - currentTimestamp)) : undefined}
Crec q podries fer servir el `useFormatDate`

2023-03-31 08:27 UTC, JordiParraCrespo commented on src/module/activity/component/navigation/SignInRequestModal/SignInRequestModal.tsx
> +        <CardSelectModal title={translate("reviewConnection")} dismissal="close" style={{ height: "95%" }} {...modalProps}>
Bon canvi! jaja

2023-03-31 08:27 UTC, JordiParraCrespo commented on src/module/activity/queries/useGetPendingTransactions.ts
> +            select: (data) => parsePendingTransactions(data),
Top!

2023-03-31 08:27 UTC, JordiParraCrespo commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.tsx
>          <TransactionRequestRoot
Et deixo algunes idees que igual es poden millorar: 
El `TransactionRequestRoot` igual pot rebre la transation i fer la logica del `expireDate` i el `amountAction` ?

2023-03-31 08:27 UTC, JordiParraCrespo commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.tsx
>      const { actionElement, handleAction } = useGetTransactionRequestAction(status);
Això es sempre `undefined`. Ara que ja estas com amb una versió més actual `refactorizaria un pelin... Dona-li una pensada a veure que es pot millorar.

2023-04-05 14:27 UTC, GuillemGarciaDev commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.tsx
>      const { actionElement, handleAction } = useGetTransactionRequestAction(status);
Aquest està deprecated, el vaig fer previ a fer el backend i un cop va quedar definit va perdre l'utilitat

2023-04-05 14:33 UTC, GuillemGarciaDev commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.styles.ts
> +    const action = "add";
Això depèn encara del tipus de `TransactionRequest` que arribi, si CKB, tokens, NFTs etc..., que no està definit. Per ara ho deshabilito i li poso un `TODO`

2023-04-05 14:51 UTC, GuillemGarciaDev commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.tsx
> +            details={expiresAt ? translate("expireDate", getTimeFromSeconds(expirationTimestamp - currentTimestamp)) : undefined}
Done

2023-04-05 14:54 UTC, GuillemGarciaDev commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.tsx
>          <TransactionRequestRoot
Esque no hauría de gestionar-ho. No se si ho has vist, però `TransactionRequestRoot` es un styled component del component `ActivityCard` que serveix tant per les `ConnectedDApps` com per les `TransactionRequests`. Per tant, tant l'`amount` com el `expireDate` son coses de la transacció en si

2023-04-14 06:46 UTC, JordiParraCrespo commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.styles.ts
> +    const action = "add";
OKey però s'ha de deixar le primary no el 200 :P Que si després canvia el primary, això ho faci tmb

2023-04-14 06:47 UTC, JordiParraCrespo commented on src/module/activity/component/display/TransactionRequest/TransactionRequest.tsx
>          <TransactionRequestRoot
solved

2023-04-14 06:47 UTC, JordiParraCrespo approved these changes

2023-04-14 06:48 UTC, merged