Signer Feature: Transaction Request Modal (with success and error handling)
Peersyst/ckbull-mobile pull request #518
Opened 2023-03-28 15:37 UTC by GuillemGarciaDev

# Signer Feature: Transaction Request Modal (with success and error handling)

## Issues

closes #505 #507 #508 

## Dependencies

#517 

## Changes

- TransactionRequestModal (modal for signing/rejecting transaction requests) 
- useSignTransactionRequests
- useRejectTransactionRequests
- TransactionRequestScreen
- SignRequestAppSummary (refactored to use it in both modals)
- SignTransactionRequestSuccess + styles
- CopyButton
- locale + testing

2023-03-31 09:02 UTC, JordiParraCrespo requested changes

2023-03-31 09:02 UTC, JordiParraCrespo commented on src/module/activity/component/display/SignRequestAppSummary/SignRequestAppSummary.tsx
> +                    <Typography variant="body3Strong" textAlign="center">
El name igual tmb ha de portar un `numerOfLines={1}` no?

2023-04-10 10:55 UTC, GuillemGarciaDev commented on src/locale/locales/el/common.json
> +    "rejectConnectionDescription": "Are you sure you want to reject this connection? This action cannot be undone.",
Noo, es diferent

2023-04-10 13:28 UTC, GuillemGarciaDev commented on src/module/common/component/feedback/SignRequestModal/SignRequestModal.tsx
> +                open={false}
True, però no estava posada a false per defecte

2023-04-12 13:54 UTC, GuillemGarciaDev commented on src/module/common/component/feedback/CopyButton/CopyButton.tsx
> +export default function CopyButton({ copyText, showToast: toast = false, toastMessage, ...buttonProps }: CopyButtonProps): JSX.Element {
`useCopyToClipboard` de la lib utilitzat al `CopyButton`

2023-04-14 06:51 UTC, JordiParraCrespo commented on src/module/common/component/feedback/CopyButton/CopyButton.tsx
> +        setCopied(true);
Ficali un timeout a false :P

2023-04-14 06:52 UTC, JordiParraCrespo approved these changes

2023-04-14 10:05 UTC, merged