[TA-2270]: Update expo & react-native dependencies
Peersyst/ckbull-mobile pull request #560
Opened 2024-02-29 14:49 UTC by GuillemGarciaDev

# [TA-2270]: Update expo & react-native dependencies

## Changes

- Updated all `package.json` dependencies
- Fixed updated dependencies errors
- Fixed linting
- Added needed mocks to `setup.tsx` and removed problematic tests

2024-03-01 08:00 UTC, AgustinMJ requested changes
També falta canviar global styles per stylesheets com a near i ckbull

2024-03-01 09:12 UTC, GuillemGarciaDev commented on src/config/config.tsx
> +                variant: "primary",
Solved, era problema dels overrides

2024-03-05 08:28 UTC, AgustinMJ requested changes

2024-03-05 08:28 UTC, AgustinMJ commented on src/module/auth/hook/useBiometrics.ts
> +    const [biometric, setBiometric] = useState<AuthenticationType>(1);
Hauriem de ficar `AuthenticationType.FINGERPRINT` en comptes de `1`

2024-03-15 12:42 UTC, merged