[TA-2578]: Add joyId address send compatibility
Peersyst/ckbull-mobile pull request #571
Opened 2024-05-21 08:35 UTC by jpeersyst

# Add joyId address send compatibility PR

## Issues

- [Add joyId address send compatibility](https://www.notion.so/1930f38fb1e94f82845dab04ac1caeca?v=64f1d5da841741cf9cb3b831e5b493e3&p=53f5ce34e817475faa98776825c62fd6&pm=s)

## Changes

- Add joyId mainnet and testnet scripts
- Add PwLockAcp testnet script

2024-05-21 08:55 UTC, JordiParraCrespo requested changes
Bona feina!! :raised_hands:  Heavy la currada de les validacions! Nomes una mini cosa, mira a veure si pots evitar la duplicacio!

2024-05-21 08:55 UTC, JordiParraCrespo commented on src/module/sdk/core/connection.service.ts
> +                ConnectionService.isJoyIdAddress(network, address)
Igual podriem mirar d,alguna manera de no duplicar el codi?
```

                isSecp256k1Blake160Address(address, this.config) ||
                isAcpAddress(address, this.config) ||
                isSecp256k1Blake160MultisigAddress(address, this.config) ||
                isOmnilockAddress(address, this.config) ||
                this.isOnepassAddress(address) ||
                this.isPwlockK1AcplAddress(address) ||
                this.isForceBridgeAddress(address) ||
                this.isBitAddress(address)
                this.isBitAddress(address) ||
                this.isJoyIdAddress(address)
```

2024-05-21 12:36 UTC, silvap-javier approved these changes

2024-05-22 07:12 UTC, JordiParraCrespo approved these changes

2024-05-22 07:12 UTC, merged